### ISSUE TITLE
Thanks for bringing this to my attention and sorry for it taking so long for me to get to.

### ISSUE THREAD

**Issue by betatester3016** [divingmule/plugin.audio.iheart#11]
Thanks for bringing this to my attention and sorry for it taking so long for me to get to. 

I've released v2.0.2 for Matrix with a fix. Check the releases tab.

_Originally posted by @divingmule in https://github.com/divingmule/plugin.audio.iheart/issues/10#issuecomment-1025122891_

**Comment by betatester3016** [comment]
Thanks for looking into this. I was unable to test till today. While the search function works as intended now, unfortunately it appears that the fix may have introduced another issue in version 2.0.2:

![screenshot00001](https://user-images.githubusercontent.com/49594656/152648463-cf282ab8-d739-4d97-90eb-939d7f9ea957.png)

Please let me know if you need a debug log.

**Comment by divingmule** [comment]
Hi, this isn't new. Kodi's player doesn't parse the stream info correctly for some stations. There's nothing I can do from the add-on side of things.

**Comment by betatester3016** [comment]
I stand corrected. I haven't been using kodi for a while and confused the kodi addon with the android apk. closing issue.
