### ISSUE TITLE
script error on xbmc 13.2

### ISSUE THREAD

**Issue by MrsAngelD** [divingmule/plugin.audio.iheart#2]
When trying to use the iheart radio plugin in xbmc 13.2. I get a script error. here's my log

http://pastebin.aquilenet.fr/?1f06fc9ce6c5dcd4#2dym7iNz5jwayddD/WT20+o1e/vdTcKEcKrz1P3txZI=

**Comment by divingmule** [comment]
Better late than never?

Sorry for not responding earlier but I've done some work. You should check out the releases.
