### ISSUE TITLE
Request: iHeartRadio.ca

### ISSUE THREAD

**Issue by NonaSuomy** [divingmule/plugin.audio.iheart#5]
Hi divingmule,

Can you please add iHeartRadio.ca content as well as it's basically the same format.

Thank you.

**Comment by newf276** [comment]
Any chance you will be updating to python 3 compatible?  For Matrix.  Willing to send you some PayPal donation.

Also, yes Canadian also would be great, again willing to donate PayPal for your time and efforts.

**Comment by divingmule** [comment]
See the latest releases.

**Comment by newf276** [comment]
> See the latest releases.

Thanks will check out the changes, very much appreciated.
