### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by newf276** [divingmule/plugin.audio.iheart#6]
Thank You for updating to Python 3, I love this add-on. 

Sorry, did not know how to comment, to say that without creating a non-existent issue.

How difficult would it be for me to edit and make it work for Canadian content?

**Comment by divingmule** [comment]
HI, I'm looking into adding support for the other countries that iheart works with. It will take quite a bit of modifications but don't let me discourage you from trying. The main thing is the api urls, instead of us.api.iheart it's ca.api.iheart for Canada.

**Comment by newf276** [comment]
Thanks very much I will have a go at it, but I am pretty much a noob, but will try the updates you suggest.  Thanks gain, very much appreciated.

**Comment by divingmule** [comment]
I've been working most of the day on this and have just about got it sorted out, I think*. I should have something in the next day or so.

**Comment by newf276** [comment]
> I've been working most of the day on this and have just about got it sorted out, I think*. I should have something in the next day or so.

Awesome, I just wasted 3 hours myself, but n luck.  I change all the api references and country codes, but only was able to triple the same channels when pulled. None of which were Canadian :). But it was fun regardless, I guess I will stick to fixing electronics, I am not much of a coder....Thanks appreciate all the effort you have put in.

**Comment by divingmule** [comment]
Haha, over the past year or so I've been getting into electronics. Mostly simple circuits with micro-controllers. I love it but the math gets over my head really quick :-\

I've made some good progress this morning. If you'd like to test swap out the default.py with this one >
[default.zip](https://github.com/divingmule/plugin.audio.iheart/files/6095449/default.zip)

**Comment by newf276** [comment]
> Haha, over the past year or so I've been getting into electronics. Mostly simple circuits with micro-controllers. I love it but the math gets over my head really quick :-\
> 
> I've made some good progress this morning. If you'd like to test swap out the default.py with this one >
> [default.zip](https://github.com/divingmule/plugin.audio.iheart/files/6095449/default.zip)

LOL..the one thing  am good at, math and circuits.  Thanks so much, I will try it out.

**Comment by newf276** [comment]
I played with it for a while, accesses all the different cuts within Canada and US, I assume it would work for the rest also.  Works great.  Minor issues of not bringing up genres, no matter what the Market I set.  However, not a big issue for me.  I am happy to use just like this is now, thanks very much.  The add to fav for add-on worked great. As does the add to Kodi favs.  Will play for the next day or two, and provide any issues or bugs that I come across.  I am located in Victoria British Columbia by the way.

**Comment by newf276** [comment]
Just wanted to say, that it has been working awesome, I arable to access all channels in US and CA without issue.  Not a big deal not having the genre work, it does everything I need.  Thanks again I really appreciate it.

**Comment by divingmule** [comment]
Hi, good to hear. If you want, when you have time give this one a run through. I fixed some stuff including the genre issue, I think*. I'll do a new release soon.
[default.zip](https://github.com/divingmule/plugin.audio.iheart/files/6104869/default.zip)
Thanks for helping.

**Comment by newf276** [comment]
Awesome..I will give it a test run.  Thanks again

**Comment by divingmule** [comment]
There are new releases, you should update, I fixed some stuff.
